Apger - adding Wiz Collector.  adding RiskAndMorty Collector.
criblio/collector-templates pull request #2
Opened 2023-11-17 19:47 UTC by apger

README.md files also included.

2023-11-17 21:55 UTC, bdalpe requested changes

2023-11-17 21:55 UTC, bdalpe commented on collectors/rest/wiz/wiz-auditlogentries.json
@apger can you preface the collector template files with `collector-`? 

e.g. `wiz-auditlogentries.json` becomes `collector-wiz-auditlogentries.json` 

Thanks!

2023-11-17 22:30 UTC, apger commented on collectors/rest/wiz/wiz-auditlogentries.json
Done.  Thanks.

2023-11-17 22:31 UTC, apger commented
Prefaced the collector template files with collector- for the Wiz collector files

2023-11-18 14:33 UTC, bdalpe approved these changes
LGTM!

2023-11-18 14:33 UTC, merged